### ISSUE TITLE
Build fails on Ubuntu

### ISSUE THREAD

**Issue by maximedegreve** [twostraws/SwiftGD#1]
/Packages/SwiftGD-1.1.0/Sources/SwiftGD.swift:206:19: error: use of unresolved identifier 'gdImageCopyGaussianBlurred'
                if let result = gdImageCopyGaussianBlurred(internalImage, Int32(radius), -1) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
Cgdlinux.gdImageGaussianBlur:1:13: note: did you mean 'gdImageGaussianBlur'?
public func gdImageGaussianBlur(_ im: gdImagePtr!) -> Int32
            ^

Any idea?

**Comment by twostraws** [comment]
Are you using an old version of Ubuntu?

**Comment by maximedegreve** [comment]
I'm on Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-53-generic x86_64)

**Comment by twostraws** [comment]
I suspect that's the problem: I was working with 16.10. I'll edit the
README to add a version number.

--

On Sun, 25 Dec 2016 at 09:54, Maxime De Greve <notifications@github.com>
wrote:

I'm on Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-53-generic x86_64)




—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/twostraws/SwiftGD/issues/1#issuecomment-269116392>, or mute
the thread

**Comment by maximedegreve** [comment]
Yes that fixed it! Thanks @twostraws

**Comment by JonasSL** [comment]
@maximedegreve Hi! I'm having the same problem. How did you get this to work?

**Comment by twostraws** [comment]
@JonasSL: Just upgrade to a more modern version of Ubuntu.
