### PR TITLE
Add guards before using optional variables (in defers)

### PR DESCRIPTION
**Pull request by mczachurski**
During build using Swift 6 (in Ubuntu 24.04) I'm expecting issues:

```
23.94 [149/1376] Compiling SwiftGD Color.swift
23.94 /build/.build/checkouts/SwiftGD/Sources/SwiftGD/Image.swift:327:24: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
23.94 325 |     public convenience init?(url: URL) {
23.94 326 |         let inputFile = fopen(url.path, "rb")
23.94 327 |         defer { fclose(inputFile) }
23.94     |                        |- error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
23.94     |                        |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
23.94     |                        `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
23.94 328 |
23.94 329 |         guard inputFile != nil else { return nil }
23.94
23.94 /build/.build/checkouts/SwiftGD/Sources/SwiftGD/Image.swift:359:24: error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
23.94 357 |         // open our output file, then defer it to close
23.94 358 |         let outputFile = fopen(url.path, "wb")
23.94 359 |         defer { fclose(outputFile) }
23.94     |                        |- error: value of optional type 'UnsafeMutablePointer<FILE>?' (aka 'Optional<UnsafeMutablePointer<_IO_FILE>>') must be unwrapped to a value of type 'UnsafeMutablePointer<FILE>' (aka 'UnsafeMutablePointer<_IO_FILE>')
23.94     |                        |- note: coalesce using '??' to provide a default when the optional value contains 'nil'
23.94     |                        `- note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
23.94 360 |
```

PR is adding 'guards' to fix an issues.

### CODE REVIEW

**Comment by twostraws** [comment]
Thank you!
